ci:
  autoupdate_schedule: monthly

exclude: ".svg|.css|^dipy/data/files"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-check
        args: ["--fix", "--show-fixes"]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
        exclude: "^doc/release_notes|^doc/old_highlights.rst"
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
  - repo: local
    hooks:
      - id: generate_requirements.py
        name: generate_requirements.py
        language: system
        entry: python tools/generate_requirements.py
        files: "pyproject.toml|requirements/.*\\.txt|tools/generate_requirements.py"
