target-version = "py310"

lint.select = [
  "I",   # isort
]

[lint.isort]
case-sensitive = true
combine-as-imports = true
force-sort-within-sections = true
no-sections = false
order-by-type = true
relative-imports-order = "closest-to-furthest"
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
