parameters:
  name: ''
  vmImage: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  pool:
    vmIMage: ${{ parameters.vmImage }}
  variables:
    AZURE_CI_WINDOWS: 'true'
    DEPENDS: "cython numpy matplotlib h5py nibabel cvxpy"
    VENV_ARGS: "--python=python"
    INSTALL_TYPE: "setup"
    EXTRA_WHEELS: "https://5cf40426d9f06eb7461d-6fe47d9331aba7cd62fc36c7196769e4.ssl.cf2.rackcdn.com"
    PRE_WHEELS: "https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com"
  strategy:
    # maxParallel: 3
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(python.version)
      architecture: 'x64'
      addToPath: true
  - powershell: |
      Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add Conda to PATH
    condition: eq( variables['INSTALL_TYPE'], 'conda' )
  - powershell: |
      Set-StrictMode -Version Latest
      $ErrorActionPreference = "Stop"
      $PSDefaultParameterValues['*:ErrorAction']='Stop'
      powershell ./ci/azure/install_opengl.ps1
    displayName: 'Install OpenGL'
    condition: eq( variables['TEST_WITH_XVFB'], '1' )
  - powershell: |
      Set-StrictMode -Version Latest
      $ErrorActionPreference = "Stop"
      $PSDefaultParameterValues['*:ErrorAction']='Stop'
      ./ci/azure/install.ps1
    displayName: 'Install dependencies'
  - powershell: |
      ./ci/azure/script.ps1
    displayName: 'Run Tests'
