.. This (-*- rst -*-) format file contains commonly used link targets
   and name substitutions.  It may be included in many files,
   therefore it should only contain link targets and name
   substitutions.  Try grepping for "^\.\. _" to find plausible
   candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   nipy, NIPY, Nipy, etc...

.. git stuff
.. _git: https://git-scm.com/
.. _github: https://github.com
.. _github help: https://help.github.com
.. _msysgit: https://gitforwindows.org/
.. _git-osx-installer: http://code.google.com/p/git-osx-installer/downloads/list
.. _subversion: https://subversion.apache.org/
.. _git cheat sheet: http://github.com/guides/git-cheat-sheet
.. _pro git book: http://git-scm.com/book
.. _git svn crash course: http://git-scm.com/course/svn.html
.. _learn.github: http://learn.github.com/
.. _network graph visualizer: http://github.com/blog/39-say-hello-to-the-network-graph-visualizer
.. _git user manual: https://git-scm.com/docs/user-manual
.. _git tutorial: https://git-scm.com/docs/gittutorial
.. _git community book: https://book.git-scm.com/
.. _git ready: http://www.gitready.com/
.. _git casts: http://www.gitcasts.com/
.. _Fernando's git page: http://www.fperez.org/py4science/git.html
.. _git magic: http://www-cs-students.stanford.edu/~blynn/gitmagic/index.html
.. _git concepts: http://www.eecs.harvard.edu/~cduan/technical/git/
.. _git clone: https://git-scm.com/docs/git-clone
.. _git checkout: https://git-scm.com/docs/git-checkout
.. _git commit: https://git-scm.com/docs/git-commit
.. _git push: https://git-scm.com/docs/git-push
.. _git pull: https://git-scm.com/docs/git-pull
.. _git add: https://git-scm.com/docs/git-add
.. _git status: https://git-scm.com/docs/git-status
.. _git diff: https://git-scm.com/docs/git-diff
.. _git log: https://git-scm.com/docs/git-log
.. _git branch: https://git-scm.com/docs/git-branch
.. _git remote: https://git-scm.com/docs/git-remote
.. _git rebase: https://git-scm.com/docs/git-rebase
.. _git config: https://git-scm.com/docs/git-config
.. _why the -a flag?: http://www.gitready.com/beginner/2009/01/18/the-staging-area.html
.. _git staging area: http://www.gitready.com/beginner/2009/01/18/the-staging-area.html
.. _tangled working copy problem: http://tomayko.com/writings/the-thing-about-git
.. _git management: http://kerneltrap.org/Linux/Git_Management
.. _linux git workflow: http://www.mail-archive.com/dri-devel@lists.sourceforge.net/msg39091.html
.. _git parable: http://tom.preston-werner.com/2009/05/19/the-git-parable.html
.. _git foundation: http://matthew-brett.github.com/pydagogue/foundation.html
.. _deleting master on github: http://matthew-brett.github.com/pydagogue/gh_delete_master.html
.. _rebase without tears: http://matthew-brett.github.com/pydagogue/rebase_without_tears.html
.. _resolving a merge: https://git-scm.com/docs/user-manual#resolving-a-merge
.. _ipython git workflow: http://mail.scipy.org/pipermail/ipython-dev/2010-October/006746.html
.. _Installing Git: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
.. _remove remote branch: https://www.git-tower.com/learn/git/faq/delete-remote-branch

.. other stuff
.. _python: https://www.python.org

.. |emdash| unicode:: U+02014

.. vim: ft=rst
