#!/usr/bin/env python
import sys
import pickle
from vis_track import gui_track
from eztrack import EZTrackingInterface

w = EZTrackingInterface()
if len(sys.argv) == 2:
    input = sys.argv[1]
    if input[-2:] == '.p':
        w = pickle.load(open(input,'rb'))
        try:
            gui_track(w)
            sys.exit(0)
        except AttributeError:
            raise ValueError('this track was not created using the gui')
    else:
        execfile(sys.argv[1])
gui_track(w)
