#!/usr/bin/env python
# vim: ft=python
""" Run pytest for dipy

Use as ``pytest`` except we always run the doctests

To reproduce a standard test run::

    dipnost /path/to/dipy/dipy

"""

import sys
import pytest

def id(self):
    name = self._dt_test.name
    filename = self._dt_test.filename
    if filename is not None:
        pk = doctests.getpackage(filename)
        if pk is None:
            return name
        if not name.startswith(pk):
            name = "%s.%s" % (pk, name)
    return name

def prepare_imports():
    # Set matplotlib backend as 'agg'
    try:
        import matplotlib as mpl
    except ImportError:
        pass
    else:
        mpl.use('agg')

if __name__ == '__main__':
    # Monkeypatch.  Yes, it's nasty
    # Set mpl backend
    prepare_imports()
    # Uses doctest by default
    pytest.main()
