name: s390x Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        run: |
          sudo apt-get install -y qemu-system-s390x qemu-user-static
          sudo update-binfmts --enable qemu-s390x
          sudo service binfmt-support start

      - name: Set up Debian s390x Environment
        run: |
          sudo debootstrap --arch s390x sid /srv/chroot/sid-390x http://ftp.fr.debian.org/debian

      - name: Install Dependencies
        run: |
          sudo chroot /srv/chroot/sid-390x apt-get update
          sudo chroot /srv/chroot/sid-390x apt-get install -y python3 python3-pip
          sudo chroot /srv/chroot/sid-390x pip3 install cython numpy==1.22.4 scipy==1.8 nibabel==3.0.0 h5py==3.1.0 tqdm

      - name: Install DIPY
        run: |
          sudo chroot /srv/chroot/sid-390x apt-get install -y python3-pip
          sudo chroot /srv/chroot/sid-390x pip3 install dipy

      - name: Run Compatibility Tests
        run: |
          sudo chroot /srv/chroot/sid-390x python3 -m dipy.test -k compat

      - name: Run Optional Tests
        run: |
          sudo chroot /srv/chroot/sid-390x python3 -m dipy.test -k optional

      - name: Run Parallel Tests
        run: |
          sudo chroot /srv/chroot/sid-390x python3 -m dipy.test -k parallel

      - name: Run Pre Tests
        run: |
          sudo chroot /srv/chroot/sid-390x python3 -m dipy.test -k pre

      - name: Run Template Tests
        run: |
          sudo chroot /srv/chroot/sid-390x python3 -m dipy.test -k template

      - name: Run Visualization Tests
        run: |
          sudo chroot /srv/chroot/sid-390x python3 -m dipy.test -k viz

      - name: Run General Tests
        run: |
          sudo chroot /srv/chroot/sid-390x python3 -m dipy.test